owner: amblerapp
repo: status

sites:
  - name: RSSBox
    url: https://rssbox.ambler.app/
  - name: RSSHub
    url: https://rsshub.ambler.app/
  - name: RSS-Bridge
    url: https://rssbridge.ambler.app/
  - name: Reddit-RSS
    url: https://reddit-rss.ambler.app/
  - name: MonitoRSS-Ambler
    url: https://monitorss.ambler.app/
  - name: MonitoRSS-Music
    url: https://music-rss.ambler.app/
  - name: MonitoRSS-Tech
    url: https://tech-rss.ambler.app/
    
status-website:
  cname: status.ambler.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ambler App Status
  introTitle: "**Upptime** for Ambler App"
  introMessage: Ambler App 모니터
